# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78aa1ba00f677b4a1cd16744053a6f6f5d049b694eb7c8196be8ec806b02174d082e7cc1e4d1d9bd8bcd7f97bb008000ff221e930f090c2cc2d3782858bbd3d7

test:
  secret_key_base: 2164e905ed4a11e0fbd4e3867d5594df0c0fbe5b074fbc4a7a516cb0760df67423c84dba99f351267a6ee5b0beb3cc242e9584ec748a5127e939ede2d413939e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
